#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npm run pre-commit

# Run type checking
npm run type-check

# Run tests for changed files
npm run test -- --findRelatedTests --passWithNoTests